### ISSUE TITLE
Random Event Plugin Bug/Issue

### ISSUE THREAD

**Issue by MysticTopHats** [runelite/runelite#10091]
I turned on the random even plugin and have two options enabled.
1. Genie event notification
2. Turn off others event.
While I was alone at Varrock castle east of GE I got the genie event. It would not let me click the genie because it thought the genie was not my RE (Random Event). I had to turn off the plugin to claim my lamp from the RE. I did not have the plugin enabled for longer than maybe an hour or two before getting the genie and I hadn't relogged or restarted the client after enabling the RE plugin. I hope this helps.

**Comment by oojava** [comment]
Similar issue just happened to me with a random that spawned in my house
![image](https://user-images.githubusercontent.com/2854960/67141630-9c36e380-f227-11e9-9a75-d55ae6dd6441.png)

![image](https://user-images.githubusercontent.com/2854960/67141711-abb62c80-f227-11e9-92d7-84429f6c191f.png)

**Comment by Nightfirecat** [comment]
@Adam- I believe this was fixed by f31e366da66e3333904bdf1a407bdcf9791a3ac1?

**Comment by hsamoht** [comment]
Still not entirely fixed.

Seems, no pun intended, random if it bugs out or not. Most events work fine. Have had it occur at least 3 times the past week. Can't remember what the first one was, but the two last ones (Yesterday and today) have been Rick Turpentine.

![](https://i.imgur.com/nbmePhM.png)
