### ISSUE TITLE
Screenshot has transparent border with custom chrome + include client frame enabled

### ISSUE THREAD

**Issue by tjb0607** [runelite/runelite#1147]
![image](https://user-images.githubusercontent.com/1190870/37962826-3a9a2790-3171-11e8-9a70-a06b07d82e3a.png)

**Comment by deathbeam** [comment]
I think this was solved already, can you recheck?

**Comment by tjb0607** [comment]
Just tried again in the snapshot, still happening

![image](https://user-images.githubusercontent.com/1190870/39400661-b74f8e9c-4ae9-11e8-904f-b610562305b4.png)

**Comment by Nightfirecat** [comment]
Seems like this is still an issue; I can reproduce it on latest client, and it has a transparent border on all edges where there is native OS chrome.

**Comment by raiyni** [comment]
I don't think this is easily fixable without modifying/removing Substance.

When you tell it to repaint heavy components, you get the border colored but no buttons nor title are drawn.

![2019-03-31_22-37-13](https://user-images.githubusercontent.com/22979513/55302665-cb127700-5407-11e9-83a1-323d255dae57.png)

You can use print to draw the native java frame but then you get the ugly look.

![2019-03-31_22-33-18](https://user-images.githubusercontent.com/22979513/55302684-e3829180-5407-11e9-9380-d34decef138d.png)

**Comment by devLotto** [comment]
> 
> 
> 
> You can use print to draw the native java frame but then you get the ugly look.
> 
> ![2019-03-31_22-33-18](https://user-images.githubusercontent.com/22979513/55302684-e3829180-5407-11e9-9380-d34decef138d.png)


Print doesn't make it include the native chrome for me on Win 10

**Comment by raiyni** [comment]
printAll is the proper one to use for it

**Comment by devLotto** [comment]
Oh I see. Why does that draw the Windows 7 titlebar even though I'm on 10, haha what the ..

**Comment by Nightfirecat** [comment]
Is this still an issue?
