### ISSUE TITLE
Fixed Mode Hide chat plugin should work more like filled mode hidden chat.

### ISSUE THREAD

**Issue by DelVision** [runelite/runelite#11615]
**Is your feature request related to a problem? Please describe.**
In the current form of the plugin it's very forceful with how it hides chat, so basically it never pops up other than with manual click. So it keeps hiding the usual stuff like level ups or NPC talking to you.

**Describe the solution you'd like**
It should just borrow the features from the filled mode when it's chat is hidden in similar way.

**Describe alternatives you've considered**
Only alternative is currently to just turn it off if I want to see the pop ups. But I prefer using fixed mode when I have multiple clients running since my filled mode for full screen play has very different settings and I use filled mode for it.

**Additional context**
Also a small bug report relating to "Fixed mode hide chat" is that the graphics on the sides of the chat are bugged and leave "ghosts" of tooltips that popped on top of them. It's relatively minor thing but still makes it look unclean. Potential solution to it would be to just add small piece of graphics on those problem spots when chat is hidden or to remove even more of the graphics when the plugin is turned on even above the chat up to top of the screen to further increase the FoV.

**Comment by Nightfirecat** [comment]
We do not maintain this plugin. Please open the plugin's support link and request this feature/enhancement on that plugin's repository.

**Comment by deathbeam** [comment]
It should be fixed now @DelVision : https://github.com/deathbeam/example-plugin/compare/f7692cb94647b0d936e046f594ecb6aadb079fe2...deathbeam:3eba8ad1cfec34f6586bd0d749abe94c48a34749

**Comment by osrsblood** [comment]
There's no reason to have an ugly bug still persistent in the plugin -- OPs additional comments: "Also a small bug report relating to "Fixed mode hide chat" is that the graphics on the sides of the chat are bugged and leave "ghosts" of tooltips that popped on top of them."   Can this be fixed or can someone point me in the direction to try and fix it myself?
