### ISSUE TITLE
sound/music stutter on login

### ISSUE THREAD

**Issue by silverhikari** [runelite/runelite#14882]
**Describe the bug**
music starts playing for a second then none for a few seconds then music plays again and over and over even though everything else runs normally
**To Reproduce**
1. start runlite
2. get to login screen

**Expected behavior**
music plays normally with out skips and stutters

**Environment (please complete the following information):**
 - OS: Manjaro/Linux
 - RuneLite version: 1.8.18.1
 - Launcher version: 2.4.2

**Additional context**
 i am using pipewire with pipewire-alsa and pipewire-pulseaudio. i have also checked the logs with no errors given except cache mismatch that was redownloaded by the client

**Comment by jolty1** [comment]
I have this problem too, happens with both the AppImage and .jar version.

It used to be work before, not exactly sure when it broke because I played with music off for a while. 

[YouTube: 30 sec video of the issue in action](https://www.youtube.com/watch?v=PaGEHkO89Gw)

**Comment by silverhikari** [comment]
yep seems to be the exact same issue as i also tried the Appimage with no luck, and i did not relize that runelite uses two alsa sound applications

**Comment by DarkArc** [comment]
I have this problem as well, I've had it at least for a couple of weeks, also using pipewire under Fedora 35.

**Comment by Fijxu** [comment]
Same problem here
Arch Linux, PipeWire, Java 11, using the runelite package from [AUR](https://aur.archlinux.org/packages/runelite)
The ALSA input appears and disappears

[Video](https://ii.zzls.xyz/LIYGFIV.mp4)

**Comment by CalebWhiting** [comment]
I'm wondering if this could be related to an issue I've been having.

First notification works (But only with custom notification sound enabled), and then subsequent notifications are mute.

Are any of you having this issue too?

**Comment by Fijxu** [comment]
> Does increasing the period-size and headroom values help the stuttering? https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Troubleshooting#stuttering-audio-in-virtual-machine

**Yes**, i was using wireplumber, i used this workaround and it worked, the music no longer stutters in login menu and in game :)

**Comment by DarkArc** [comment]
> > Does increasing the period-size and headroom values help the stuttering? https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Troubleshooting#stuttering-audio-in-virtual-machine
> 
> **Yes**, i was using wireplumber, i used this workaround and it worked, the music no longer stutters in login menu and in game :)

This didn't help me, what did you set the values to?

**Comment by Fijxu** [comment]
> This didn't help me, what did you set the values to?

Yeah i was wrong, it worked for some seconds but i was in a place with much noise so i didn't notice, srry

**Comment by Nightfirecat** [comment]
Does `pw-top` indicate any issues for those experiencing stuttering?

**Comment by DarkArc** [comment]
> Does `pw-top` indicate any issues for those experiencing stuttering?

I'm not sure what an "issue" would be. It doesn't look that different from any other audio processes, it just spawns, plays for a couple seconds, does nothing for a couple of seconds, disappears, then comes back and plays for a couple of seconds, rinse repeat.

**Comment by Jay-Aberlour** [comment]
I have the same problem on Fedora 36.

Although I do not know what it means, I found something peculiar. When looking at my sound menu in gnome, I constantly see a new bar of "ALSA plug-in [java]" appear and disappear. The few seconds when the sounds are back are the one where a new instances has appeared, then it is quite for a while and the the second alsa-bar disappears. I have added screenshots in the hope that provides more information.
![Screenshot from 2022-05-14 00-11-43](https://user-images.githubusercontent.com/36713023/168395933-c1648929-5086-456e-b080-0f4fa3d8b65a.png)
![Screenshot from 2022-05-14 00-12-19](https://user-images.githubusercontent.com/36713023/168395935-a48b214a-2b17-4e01-a9c3-8b0afddf31e9.png)

**Comment by tooPunkForTP** [comment]
Having the same problem. Game and area sounds work fine, music stutters. 
~:pipewire -V
`Compiled with libpipewire 0.3.51
Linked with libpipewire 0.3.51` 

~:pipewire-media-session
`Compiled with libpipewire 0.3.40
Linked with libpipewire 0.3.51`

~:pipewire-pulse -V
`Compiled with libpipewire 0.3.51
Linked with libpipewire 0.3.51` 

and using pipewire-pulse of the same version #

I'm having the same symptom as @Jay-Aberlour where a java source will appear and disappear in my patchbay, but the timing does not appear to be correlated as far as I can tell (see [here](https://streamable.com/44swfm).

Since I use pipewire-media-sesion instead of wireplumber, I'll see if I can adapt Nightfirecat's fix mentioned earlier in the thread a shot and update here when I do.

**Comment by hankjordan** [comment]
Similar issue #3525

May be related to an outdated Java version.

Installing Runelite from AUR and updating JRE to <code>openjdk 18.0.1.1</code> resolves my sound issue entirely.

**Comment by Jay-Aberlour** [comment]
idk if #3525 is a similar issue: I've seen a FAQ-issue which solves exactly this.

For me, although I am using a flatpak on Fedora, installing Java 18 does not solve the issue. I am interested in trying to solve this myself and maybe adding a pull request. Can somebody tell me where the sound in handled in this project? Maybe @Nightfirecat?

**Comment by hankjordan** [comment]
@Jay-Aberlour I only mention that issue because I was also having the same thing happen, with <code>ALSA plug-in [java]</code> popping up and disappearing. After I got audio working, the entries changed to <code>PipeWire ALSA [java]</code>.

**Comment by DarkArc** [comment]
> idk if #3525 is a similar issue: I've seen a FAQ-part which solves exactly this.
> 
> For me, although I am using a flatpak on Fedora, installing Java 18 does not solve the issue. I am interested in trying to solve this myself and maybe adding a pull request. Can somebody tell me where the sound in handled in this project? Maybe @Nightfirecat?

The flatpak uses its own bundled Java isolated from the system so that wouldn't help. I've opened an issue on the flatpak to see about a version bump. Ideally someone else should confirm the Java 18 bump fixes it (when run outside of the flatpak).

**Comment by Jay-Aberlour** [comment]
@DarkArc Good remark. When updating to Java 18 the sound problem does indeed solve.

**Comment by Fijxu** [comment]
I can confirm it's working in `openjdk 18.0.1.1 2022-04-22`
Arch Linux with pipewire-media-session
ALSA input no longer disappears 

![23-224206](https://user-images.githubusercontent.com/61166695/169938077-f852a3c6-4cec-4cf1-98f2-d871f75dba78.png)

**Comment by Jay-Aberlour** [comment]
Maybe a noob question (sorry beforehand), but do we know why this fixes it?

**Comment by hankjordan** [comment]
> Maybe a noob question (sorry beforehand), but do we know why this fixes it?

I think Java 11 might be bypassing pipewire/pulseaudio, accessing ALSA directly, while Java 18 does it correctly.

**Comment by Adam-** [comment]
If someone can bisect openjdk upstream to find what commit fixes this issue, that would help us figure out what is happening.

**Comment by DarkArc** [comment]
More than likely this is just that pipewire is very new, and there's support needed in the JVM that wasn't added until 18 (seeing as the new audio channels _seem_ to be using pipewire more directly).

**Comment by Jay-Aberlour** [comment]
Alright, so I've tested this for about half and hour: everything seems to work fine with java18. Meaning: updating to J18 would solve this issue.

**Comment by silverhikari** [comment]
seems not to have fixed it on my side when running the the version from the aur as i still have the audio glitch and the audio outputs are still labeled ALSA plug-in [java]
java version: openjdk 18.0.1.1 2022-04-22
pipewire: 0.3.51
wireplumber: 0.4.10

**Comment by hankjordan** [comment]
> seems not to have fixed it on my side when running the version from the aur as i still have the audio glitch and the audio outputs are still labeled ALSA plug-in [java] java version: openjdk 18.0.1.1 2022-04-22 pipewire: 0.3.51 wireplumber: 0.4.10

You should also uninstall <code>pulseaudio-alsa</code> if it's installed, install <code>realtime-privileges</code> and add your user to the <code>realtime</code> group

**Comment by silverhikari** [comment]
also fixed things for me as it seems pulseaudio-alsa was still installed

**Comment by clscndd** [comment]
> > seems not to have fixed it on my side when running the version from the aur as i still have the audio glitch and the audio outputs are still labeled ALSA plug-in [java] java version: openjdk 18.0.1.1 2022-04-22 pipewire: 0.3.51 wireplumber: 0.4.10
> 
> You should also uninstall `pulseaudio-alsa` if it's installed, install `realtime-privileges` and add your user to the `realtime` group

I'm currently using Pop-OS 22.04 LTS, so this solution couldn't work for me. Is there a "realtime-privileges" equivalent for Pop/Ubuntu? Uninstalling pulseaudio didn't work either. If anyone can help, I'd be grateful.

My Java version is 18.0.2

**Comment by silverhikari** [comment]
@clscndd this may help setting up realtime on your system though it is for jack https://jackaudio.org/faq/linux_rt_config.html

**Comment by clscndd** [comment]
@silverhikari Thanks for your answer, the guide was very instructive; I successfully got my user into the audio group. However, nothing else changed, the audio issue persists. Did I forgot something?

**Comment by silverhikari** [comment]
@clscndd did you uninstall pulseaudio-alsa since that may hang around even if you uninstall the main pulseaudio

**Comment by clscndd** [comment]
@silverhikari Yes, I did. No results so far, unfortunately :(. `pactl info` returns:

`PulseAudio (on PipeWire 0.3.56)`

As I think theres no way to completely remove PulseAudio, this is probably the best I can do.

**Comment by ruineka** [comment]
The flatpak still does not have a fix for the audio to this day, using the appimage provided on the website works fine on Arch Linux, but on Pop OS 22.04 it cuts out. I haven't looked at the Java version on Pop but I'm guessing this isn't part of the appimage so this is likely what needs updated for it to work like it does on Pop.

**Comment by clscndd** [comment]
Hey @ruineka thanks for the info. I tried the snap version of RuneLite, but I got the same issues I don't know if using the snap version should fix the problem tho. Anyway, it's not the same thing playing with the sound cutting like that, so I think I'll just wait for the Jagex Launcher or play on steam. I'll miss the HD Plugin tho.

**Comment by leynebe** [comment]
I have the same issue running pop_os. Sound cuts out randomly and you can see the sound process(?) appear and disappear in the sound settings. Running the Runelite `.jar` with java18 does not solve it, not does any of the other solutions discussed in this thread.
I'm willing to try solutions if anyone has any.

**Comment by MrCarroll** [comment]
Out of curiosity, can you try the `openjdk-8-jre` package, assuming you're on Ubuntu/Debian/derivatives.

It's been well over a decade so my memory might be imperfect here, but the Debian 8 Java release had Pulseaudio native support, which was later dropped in newer JVM's to rely on the Alsa/Pulse wrappers which were considered good enough. You might find you have better results with the Pulseaudio backend than the ALSA backend.

You'll need to run via older versions of RuneLite's launcher that are compatible with Java 8 (e.g the 1.6 releases)

**Comment by gridlocdev** [comment]
@MrCarroll Can confirm audio plays again successfully without stutters on my Pop!_OS 22.04 running the `.jar` from the [1.6.2 launcher](https://github.com/runelite/launcher/releases/tag/1.6.2) release with `openjdk-8-jre`.

Running this works for me (where `RuneLite.jar` is from a version 1.6.x)
```shell
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar ~/Downloads/RuneLite.jar
```

Notably like you mentioned this also fails as expected on any launcher versioned 2.0.0 and later. Running the above `openjdk-8-jre` call on post-2.0.0 launcher versions (tested 2.0.0 and 2.1.3) fails to launch and outputs a Java version runtime exception since those versions presumably don't include Java 8 support:
```shell
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/runelite/launcher/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by DarkArc** [comment]
The general direction in the "Desktop Linux" space seems to be to move towards PipeWire (which works for the folks on Java 18+). I'd say the "best fix" (if possible) is to upgrade to PipeWire and Java 18 in your environment.

**Comment by aHooder** [comment]
For people where the audio is cutting out for multiple seconds at a time (not crackling or very brief stuttering), I think the issue lies with the Flatpak version of RuneLite. Try the AppImage from RuneLite's website instead.

I didn't figure out why, but my guess is it has to do with some sort of sandboxing. Also worth noting that Java applications can't interface directly with Pulseaudio or PipeWire, and require the `pulseaudio-alsa` or `pipewire-alsa` packages respectively (package names may vary with distro).

**Comment by DarkArc** [comment]
> For people where the audio is cutting out for multiple seconds at a time (not crackling or very brief stuttering), I think the issue lies with the Flatpak version of RuneLite. Try the AppImage from RuneLite's website instead.
> 
> I didn't figure out why, but my guess is it has to do with some sort of sandboxing. Also worth noting that Java applications can't interface directly with Pulseaudio or PipeWire, and require the `pulseaudio-alsa` or `pipewire-alsa` packages respectively (package names may vary with distro).

As noted here (https://github.com/flathub/net.runelite.RuneLite/issues/16) the issue is with the flatpak using a pre-Java 18 version of Java. From what I gather, there may then be a _further_ complication if the system is _also_ using PulseAudio instead of PipeWire.

**Comment by aHooder** [comment]
> > For people where the audio is cutting out for multiple seconds at a time (not crackling or very brief stuttering), I think the issue lies with the Flatpak version of RuneLite. Try the AppImage from RuneLite's website instead.
> > I didn't figure out why, but my guess is it has to do with some sort of sandboxing. Also worth noting that Java applications can't interface directly with Pulseaudio or PipeWire, and require the `pulseaudio-alsa` or `pipewire-alsa` packages respectively (package names may vary with distro).
> 
> As noted here ([flathub/net.runelite.RuneLite#16](https://github.com/flathub/net.runelite.RuneLite/issues/16)) the issue is with the flatpak using a pre-Java 18 version of Java. From what I gather, there may then be a _further_ complication if the system is _also_ using PulseAudio instead of PipeWire.

I can't confirm Java 18 fixes it, though it may. Whatever difference the Flatpak makes vs. the AppImage, I was able to reproduce the bug on a fresh install of Fedora 36 (pipewire) with the Flatpak version, but not with the AppImage. If I remember correctly, the AppImage uses Java 11.

**Comment by leynebe** [comment]
> The general direction in the "Desktop Linux" space seems to be to move towards PipeWire (which works for the folks on Java 18+). I'd say the "best fix" (if possible) is to upgrade to PipeWire and Java 18 in your environment.

I agree, the problem is that those parameters do not solve the issue.
As far as I know I'm using pipewire:
```
$ pactl info | grep "Server Name"
Server Name: PulseAudio (on PipeWire 0.3.56)
```
And tried executing the latest RuneLite.jar with both the java11 openjdk and java18 openjdk, the issue persists.
The only way I've gotten the sound to work is by using RuneLite.jar v1.6.2 with java8. (https://github.com/runelite/runelite/issues/14882#issuecomment-1224407410)


> For people where the audio is cutting out for multiple seconds at a time (not crackling or very brief stuttering), I think the issue lies with the Flatpak version of RuneLite. Try the AppImage from RuneLite's website instead.
> 
> I didn't figure out why, but my guess is it has to do with some sort of sandboxing. Also worth noting that Java applications can't interface directly with Pulseaudio or PipeWire, and require the `pulseaudio-alsa` or `pipewire-alsa` packages respectively (package names may vary with distro).

I have not used the RuneLite Flatpak.
I actually first encountered the issue using the latest RuneLite.AppImage a week or 2 ago when I started playing again, and only when I found this thread did I start messing around with the .jar and different java versions. The issues stay the same: `audio is cutting out for multiple seconds at a time (not crackling or very brief stuttering)`. (Exactly like @Fijxu's experience of this same thread: https://github.com/runelite/runelite/issues/14882#issuecomment-1107881047)

**Comment by aHooder** [comment]
@leynebe Have you ensured that you have `pipewire-alsa` installed? Also make sure you don't have `pulseaudio-alsa` installed simultaneously, as I think the configs may interfere.

**Comment by leynebe** [comment]
As I mentioned earlier, I run pop_os so package names might differ, but it seems `pipewire-alsa` is installed and `pulseaudio-alsa` is not even available.
```
➜  ~ sudo apt list pipewire-alsa         
pipewire-alsa/jammy,now 0.3.56-0pop1~1658336739~22.04~a3894c2 amd64 [installed]
pipewire-alsa/jammy 0.3.56-0pop1~1658336739~22.04~a3894c2 i386
➜  ~ sudo apt list pulseaudio-alsa
(None)
```

**Comment by gridlocdev** [comment]
> Have you ensured that you have `pipewire-alsa` installed? Also make sure you don't have `pulseaudio-alsa` installed simultaneously, as I think the configs may interfere.

Pop!_OS 22.04 comes with Pop's [self-packaged version of pipewire](https://github.com/pop-os/pipewire) with `pipewire-alsa`, and `pulseaudio-alsa` isn't available in the default repositories that I can see:
![image](https://user-images.githubusercontent.com/60323737/186449917-4f4e00e1-6765-4e04-aa0a-c243135dbc4f.png)

I've personally also tried all versions that Runelite is packaged in, the Snap, AppImage, Flatpak, and `.jar` all have the same several second intermittent cutout issue in the same exact frequency on the most recent launcher versions.

**Comment by aHooder** [comment]
Hmm, strange. I'm not sure what might be the issue for you guys then. Maybe it'd be worth manually looking through files in `/etc/alsa/conf.d/`?

**Comment by aHooder** [comment]
Maybe you have to manually add [this file](https://github.com/pop-os/pipewire/blob/master_jammy/pipewire-alsa/conf/99-pipewire-default.conf) to `/etc/alsa/conf.d/`?

**Comment by leynebe** [comment]
That fixed it for me, thanks all! Now I can enjoy the incredible music this game offers once again. :)

I found `/etc/alsa/conf.d/99-pipewire-default.conf`, which contained:
```
# Default to `type pulse` to fix audio lag from `type pipewire`
pcm.!default {
    type pulse
    hint {
        show on
        description "Default ALSA Output (currently PulseAudio Sound Server)"
    }
}

ctl.!default {
    type pulse
}
```

I replaced it with the file from @aHooder's comment (https://github.com/runelite/runelite/issues/14882#issuecomment-1225852335):
```
pcm.!default {
    type pipewire
    playback_node "-1"
    capture_node  "-1"
    hint {
        show on
        description "Default ALSA Output (currently PipeWire Media Server)"
    }
}

ctl.!default {
    type pipewire
}
```

Not sure what it does though, are we increasing the priority for pipewire to be used as default?
I did notice `type pulse` in the previous file. Was I using pulseaudio all along?

**Comment by aHooder** [comment]
> Not sure what it does though, are we increasing the priority for pipewire to be used as default?
I did notice type pulse in the previous file. Was I using pulseaudio all along?

The main thing seems to be to instruct it to go to `pipewire` instead of `pulse`. From the [doc here](https://fossies.org/linux/alsa-plugins/doc/README-pulse) it seems like this would let RuneLite (Java) interface with PipeWire's sound daemon through ALSA API? Not entirely sure myself.

**Comment by 1player** [comment]
FWIW, I've been testing OpenJDK 18 compiled locally with the RuneLite flatpak, compiled locally as well, but audio is still broken.

So, as others have said, upgrading your JDK isn't enough. Any ideas?

**Comment by DarkArc** [comment]
> FWIW, I've been testing OpenJDK 18 (the flatpak version) compiled locally, with the 22.08 freedesktop SDK and the RuneLite flatpak, compiled locally as well, but audio is still broken.
> 
> So, as others have said, upgrading your JDK isn't enough. Any ideas?

Are you using pipewire or pulse?

It might be a situation that upgrading the JDK in or outside of the flatpak fixes it if you're using pipewire but not if you're using pulse (that's another trend I recall seeing with this).

**Comment by 1player** [comment]
> Are you using pipewire or pulse?

I'm on pipewire. Fedora Silverblue 36, GNOME.

I've opened an issue upstream: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2674

**Comment by 1player** [comment]
There's a workaround for the Flatpak version of Runelite: https://github.com/flathub/net.runelite.RuneLite/issues/16#issuecomment-1236391579

Probably preferable to messing up your ALSA configuration. Be aware that upgrading to OpenJDK 18 by itself **doesn't** necessarily solve the issue.

**Comment by aHooder** [comment]
> EDIT: The workaround is using the configuration from @leynebe, it fixes the audio in game BUT breaks any other audio application. Can't listen to Spotify while RuneLite is active. So it's a different kind of annoying.

I wouldn't call it messing up your ALSA configuration. It shouldn't break all other audio, so you might have some other interfering configuration in the mix. Did you try changing this configuration system-wide?

**Comment by 1player** [comment]
> I wouldn't call it messing up your ALSA configuration. It shouldn't break all other audio, so you might have some other interfering configuration in the mix. Did you try changing this configuration system-wide?

No, that's the point. I don't want to change my system-wide configuration to work around a problem that affects this game only. Also because I run Silverblue.

I am trying to work around this issue when using the Flatpak version, and I can only affect the game's ALSA configuration, but as explained above, it kills audio from other apps. 

See the pipewire issue I linked, I've been asking with the pipewire devs for help to figure out what's going on here. At first glance it seems OpenJDK interacts with Pulseaudio in a specific way that the pipewire-pulse bridge isn't happy with. Might be a Java bug, or a pipewire bug, or perhaps might even be fixed by RuneLite (if there's a way to talk directly with pipewire instead of going through the pulse-compatible API).

**Comment by 1player** [comment]
Good news everybody, it's fixed in pipewire master: https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/a79b5c86ea33d7103c07552ecbbde54e1c01e7bd

The latest tag is 0.3.57, so perhaps it'll be ready when pipewire 0.3.58 hits your distro package manager.

**Comment by 1player** [comment]
Confirmed fixed with pipewire 0.3.58, tested on Fedora Silverblue.
