### ISSUE TITLE
ground items: only show own items not working

### ISSUE THREAD

**Issue by YvesW** [runelite/runelite#17834]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Reported by discord user thelip6733 (808050150534545508).
He's a regular ironman (grey helm) that still sees the loot of other players, even with the ``only show own items`` option checked. Reproducable in safe mode. Please see the vid below, in which you can see he's in safe mode, the option is enabled, loot from another player has ground item text above it, and nothing happens when he tries to pick it up (iron).

https://github.com/runelite/runelite/assets/7929021/3103aafe-4e81-42a1-bbba-28e9353bf42b

I suspect this is because of https://discord.com/channels/301497432909414422/419891709883973642/1233970732250431508

### RuneLite version

RL 1.10.29

### Logs

[client(5).log](https://github.com/runelite/runelite/files/15287558/client.5.log)
[launcher(2).log](https://github.com/runelite/runelite/files/15287559/launcher.2.log)

**Comment by Adam-** [comment]
If someone with an ironman can figure out what the ownership mode of these items are that would be useful

**Comment by DapperMickie** [comment]
![image](https://github.com/runelite/runelite/assets/10809203/7ffdabde-4a6d-400c-84b6-9e54a5991aec)
![image](https://github.com/runelite/runelite/assets/10809203/44560473-ae48-482d-b5f0-11a533c01151)
Im an iron, the guy that got the drops was a main

**Comment by DapperMickie** [comment]
If the other person is a group iron (blue helm) it does show up correctly as ownership 2
![image](https://github.com/runelite/runelite/assets/10809203/5c837941-a34a-4692-8886-bfb9c669f66a)

**Comment by Adam-** [comment]
So if I am reading this right:

Ironman viewing a main's drop -> GROUP
Ironman viewing a gim's drop -> OTHER?

**Comment by itsjattie** [comment]
Not sure if this is the same issue, but since the option changed from `only show loot` to `only show own items`, as a main I can now see item spawns and other players' loot/dropped items.

**Comment by TheWolfie96** [comment]
Observing the same behaviour on both my main and my buddies iron, the `only show own items` setting just doesn't seem to do anything for either of us. And as mentioned above, world spawns are now showing regardless of the setting too, which they didn't prior.

**Comment by YvesW** [comment]
The ground spawns not showing was just a previous limitation. The client could not determine if you were able to pick it up as an iron, or if it was someone else's drop. For this reason it'd also incorrectly hide arrows you shot yourself (if you weren't using an assembler).

**Comment by DapperMickie** [comment]
> So if I am reading this right:
> 
> Ironman viewing a main's drop -> GROUP Ironman viewing a gim's drop -> OTHER?

Yes that seems to be it, i would want to do further testing with iron drops, hcgim and green helms to see what those values are.

**Comment by Adam-** [comment]
Ive learned that non-gim loot gets reported to other non-gims as GROUP loot due to them both having group id -1. This is probably a Jagex bug, but I've worked around it in https://github.com/runelite/runelite/commit/622c5152ea2e96caa97106961a15ed6e39acc2d2. I also restored the previous behavior of not showing unowned items.

**Comment by JadizBeard** [comment]
This issue is still ongoing. Do I need to add this to a different ticket? The previous behaviour isn't working.

![image](https://github.com/runelite/runelite/assets/169752392/afd4d4a4-023d-4c62-8e20-fbc6aa1bb3d5)

**Comment by DapperMickie** [comment]
There hasn't been an update to the runelite client yet, this issue should be resolved as soon as the next update is released :)

**Comment by vahnx** [comment]
> There hasn't been an update to the runelite client yet, this issue should be resolved as soon as the next update is released :)

I'm on RuneLite Client 1.10.38.1 and I still see other people's drops with "Only show own items" checked.

**Comment by MosheBenZacharia** [comment]
> > There hasn't been an update to the runelite client yet, this issue should be resolved as soon as the next update is released :)
> 
> I'm on RuneLite Client 1.10.38.1 and I still see other people's drops with "Only show own items" checked.

Are you a group ironman? When you say "See other people's drops" do you mean the white text on top of the item?

**Comment by vahnx** [comment]
> > > There hasn't been an update to the runelite client yet, this issue should be resolved as soon as the next update is released :)
> > 
> > 
> > I'm on RuneLite Client 1.10.38.1 and I still see other people's drops with "Only show own items" checked.
> 
> Are you a group ironman? When you say "See other people's drops" do you mean the white text on top of the item?

I'm a regular ironman and it's in reference to the item itself (not the text). It does say when you mouse over the text "Only show own items" **Only shows items that are yours or you can pickup**. Is this in reference to just the text or the item itself?

**Comment by MosheBenZacharia** [comment]
> Is this in reference to just the text or the item itself?

Just the overlay (text), notifications, and loot beams . Hiding the item model itself would probably be undesirable.

**Comment by flallnatural** [comment]
Any update on this? I don't see the option at all in Runelite now?

**Comment by Felanbird** [comment]
> Any update on this? I don't see the option at all in Runelite now?

It was replaced with the `ownership filter` options, afaik they all work as expected now except for what was reported in #18431 which we probably can't fix
