### ISSUE TITLE
Zaff battlestaves reminder still showing up after collection

### ISSUE THREAD

**Issue by defnoob** [runelite/runelite#1913]
![image](https://user-images.githubusercontent.com/8947593/39241856-8a3ba50c-4888-11e8-93c8-a8aeb562cb5c.png)

The reminder to claim staves still shows up even after they have been collected.

**Comment by Infinitay** [comment]
Fixed in #1129

**Comment by Nightfirecat** [comment]
Fixed by #5212?

**Comment by deathbeam** [comment]
I think so

**Comment by JasontheBlac** [comment]
This either has still not been fixed or there is another error because I'm still having this problem as of Aug. 2019

**Comment by Nightfirecat** [comment]
@trimbe and I couldn't reproduce this. Please make sure to re-log if you receive this notification while already logged in. Staves don't restock unless you've logged in after that point.
