### ISSUE TITLE
Sidebar is hidden in certain condition.

### ISSUE THREAD

**Issue by Juzzephe** [runelite/runelite#2612]
Reproduce :
Hide sidebar in restored mode > maximize > show side bar > restore

![ezgif-1-73afb0325e](https://user-images.githubusercontent.com/25037124/39941381-ae5b9d4e-555c-11e8-806f-4588bf67c457.gif)

On both versions 1.3.8 and 1.3.9

**Comment by valryk** [comment]
Have similar issue myself. Sometimes the sidebar interface just flashes and glitches between all of the different options available. Renders it completely useless as I can no longer use it.

**Comment by Juzzed** [comment]
You need to disable Hardware acceleration. https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by Kamielvf** [comment]
I cannot reproduce this issue, it might have been resolved among some of the UI updates.

**Comment by deathbeam** [comment]
This is quite old, I guess we can close it and reopen if needed.

**Comment by Nightfirecat** [comment]
This still appears to be a valid bug from what I can tell. The gif below is captured on release 1.6.17.

![](https://user-images.githubusercontent.com/2199511/83216493-e9cde400-a158-11ea-9209-288a747bcb05.gif)

**Comment by Adam-** [comment]
It seems like something has since changed this to make it so you cannot expand only the side bar anymore, but instead also the panel. Following the steps in OP though now leads to this which seems very broken:
![image](https://user-images.githubusercontent.com/309739/124397866-83fb4680-dce0-11eb-888c-570d778f1f29.png)

**Comment by Adam-** [comment]
fixed in 38f1d2e71fd6ed17bb56d0baad463feaac1a8575
