### ISSUE TITLE
[New UI] Focused number background color is too similar to the text highlight color

### ISSUE THREAD

**Issue by xaviergmail** [runelite/runelite#3042]
This makes it difficult to see the highlighted text:

In this picture, "1,0" is selected
![](https://xavie.ru/i/lZ7QPL)

**Comment by psikoi** [comment]
My bad, forgot to apply the new highlight colors, will fix asap.

See the ge search or hiscores for the correct colors.

**Comment by psikoi** [comment]
Fixed locally, will upload a PR soon with a few ui fixes.

![](https://i.gyazo.com/23aa6d3424c316ccbb94b5efa7e187ac.png)

**Comment by Nightfirecat** [comment]
@xaviergmail Don't close this issue--it's not fixed until #3061 is merged!
