### ISSUE TITLE
"Iconify" crashing the client and not working on MacOs

### ISSUE THREAD

**Issue by Pluginrs** [runelite/runelite#3223]
Please fix the "iconify" issue on MacOS... When trying to minimize the client, the "iconify" button remains highlighted after clicking, but does not minimize the client. Additionally, the sidebar becomes frozen and other options cannot be clicked on. Other than that, the client is amazing!

Thanks in advance.

**Comment by SoyChai** [comment]
Does this happen in both native window mode and custom chrome mode? (-> RuneLite settings)

**Comment by Pluginrs** [comment]
Now... once i disable the custom window chrome i can minimize the window but can't see the sidebar now xd

![captura de ecra 2018-05-24 as 17 32 54](https://user-images.githubusercontent.com/39594977/40498998-874c37c4-5f78-11e8-8c7e-6605623ebaf8.png)

**Comment by deathbeam** [comment]
I believe i fixed this once before, probably was reintroduced with the changes in how we resize the frame.

**Comment by Gamer1120** [comment]
Try control + F11 or command + F11 to bring up the sidebar. Maybe it works.

**Comment by Pluginrs** [comment]
Tried control + F11 but the issue still remains. Even locked client size and tried to press control + F11 but the sidebar remains hidden. I will just wait for the next update. Hopefully it will be fixed soon, so Mac users can also experience 100% this amazing client =)
