### ISSUE TITLE
Bug Report: Vertical Monitor Full Screen

### ISSUE THREAD

**Issue by WasabiCannon** [runelite/runelite#3279]
Monitor Resolution: 1080 x 1920
Portrait Mode

When did the issue start: Version 1.4.0

When RuneLite is in full screenmode on a portrait mode monitor it will not format correctly and format itself as if the monitor was in landscape mode.

If you close RuneLite at this point and reopen it you will get the following.
![runelite_2018-05-25_00-47-10](https://user-images.githubusercontent.com/17398487/40526752-8f40aa76-5fb6-11e8-91d4-15403ba9cc0f.png)
![runelite_2018-05-25_00-45-42](https://user-images.githubusercontent.com/17398487/40526753-8f496b98-5fb6-11e8-8573-a41f2417ff5b.png)

Double clicking the title bar will return it to window mode then restarting RuneLite will fully resolve the issue.

Did not see any other reports of this so figured Id throw it up just incase someone else runs into this issue.

**Comment by deathbeam** [comment]
What if you try disabling custom window chrome?

**Comment by Vigilantly** [comment]
I'm getting this issue as well. 
1080 x 1920 vertical monitor
RuneLite 1.6.18.1
OSRS Rev 189
Launcher 1.5.2

If I try to max-size RuneLite on my portrait monitor, it tries to treat it as a landscape monitor. Is it treating the resolution as a 1920 x 1080? Maybe it just needs to be able to switch the resolution variables if it detects a vertical monitor. 

It still does it if I disable "custom window chrome" under the RuneLite settings.

**Comment by Adam-** [comment]
I think this is fixed in f7606c7acaf25331331e85d4d1bad7b8e2ff3e9c - reopen if it isn't, and include which launcher version you are using.

**Comment by Vigilantly** [comment]
Hi @Adam- 

Unfortunately, this is still happening for me on my vertical monitor. I saw your commits and was stoked for the update, but after I re-launched RuneLite into 1.6.27 it was still happening for me when I try to go full screen.

Here's a photo of how it looks from a screenshot. Left side is my main (center) monitor and the right side is how it treats my vertical screen as if it's a horizontal screen when maximized.
![runelite full screen vertical monitor sample](https://user-images.githubusercontent.com/22863539/94108351-01aa3180-fdf4-11ea-8df0-4301a7796fe1.png)

1080 x 1920 vertical monitor
RuneLite 1.6.27
OSRS Rev 191
Launcher 2.1.3

I saw there was a 2.1.4 version of the launcher on GitHub, but the RuneLite.net download gave me 2.1.3

**Comment by Adam-** [comment]
We're going to do a launcher release (2.1.5) to update to Java 11.0.8 which I think will fix this. You could try running the multi platform launcher with 11.0.8 and see if it works.

**Comment by Adam-** [comment]
@Vigilantly try now with the new launcher.

**Comment by Vigilantly** [comment]
@Adam- huzzah! It works! I am able to maximize on my vertical monitor and it does fullscreen perfectly! No issues with it treating it like the wrong size monitor.

The only bug-testing note worth mentioning is that I can't drag the full-screen client to another monitor. If I try to drag the full-screen client to another monitor, it flashes on the new screen for a split-second, then stays on the original screen in maximized form. If I then un-maximize (restore) it on the original screen, it pops to the new screen in an un-maximized form. To get it to work well, I have to un-maximize (restore), move to another window, then re-maximize. Not a problem at all, but thought you might want to know.

Thank you very much for working on and fixing this! Very glad to not have the manually resize the client to fit full-screen on my vertical monitors every time I move it around.

**Comment by cnkeats** [comment]
I am still encountering this issue on launcher v2.1.6
![image](https://user-images.githubusercontent.com/8659630/102639799-29711300-411f-11eb-8fe5-0de9042b3c7e.png)

**Comment by Adam-** [comment]
This issue is about vertical monitor screens, which your screenshot is obviously not of. I assume instead you are referring to that it doesn't expand to include the hidden taskbar....?

**Comment by cnkeats** [comment]
You are correct; I commented on the incorrect issue. My apologies - I should have commented on issue #5153 and so have moved my comment there.
