### ISSUE TITLE
GPU plugin - Client crash when entering house (AMD)

### ISSUE THREAD

**Issue by JEKleine** [runelite/runelite#6543]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When entering my house or just enabling the GPU plugin inside my house the client crashes.

**To Reproduce**
1. Enable gpu plugin
2. enter house
3. Crash

**Screenshots**
My house:
![image](https://user-images.githubusercontent.com/10517253/48663917-57df1880-ea97-11e8-9a63-decea15e3f82.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.0
 - Launcher version: unknown
- CPU: Ryzen 5 1600
- GPU: RX 470 MSI
- RAM: 8GB

**Comment by MagicfTail** [comment]
Please also post your specs

**Comment by JEKleine** [comment]
> Please also post your specs

Edited with specs.

**Comment by SeaShanty3** [comment]
I have the same issue, the plugin works perfectly fine anywhere else

OS: Windows 10
Runelite version: 1.5.0
CPU: Intel core i5 6600K CPU
GPU: Radeon RX 480
RAM: 8GB

**Comment by deathbeam** [comment]
I think this is fixed with <https://github.com/runelite/runelite/commit/3286594d6b583aa261483a73ddf30823c102e923>. Can you retest this @JEKleine  ? Or anyone that had this issue

**Comment by deathbeam** [comment]
This also happens when entering house from fairy ring

**Comment by WLoumakis** [comment]
I'm still getting this issue, @deathbeam . Same specs as OP except RuneLite is up to date (1.5.2.1) and processor is Intel i5-4670K. Also seems to happen when going into the abyss for runecrafting. Logs don't show anything out of the ordinary (though they were showing NPEs on 1.5.1 launcher for another issue relating to getSprite and the clan chat manager class).

Entering house works fine with GPU plugin disabled, but as soon as it is enabled it freezes/crashes (either case the log shows nothing bad).

Maybe it has something to do with draw distance being greater than the view itself? Not sure, but it's kind of annoying because the GPU plugin is amazing! Let me know if you need more info!

**Comment by Nembience** [comment]
I'm having the same issue but with an Intel i7-7700K and a GTX 980ti (It's never happened prior to this update 1.5.6)

**Comment by MESLewis** [comment]
Join us at https://runelite.net/discord in the #support channel so we can fix this issue for you.

**Comment by Nightfirecat** [comment]
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.
