### ISSUE TITLE
Grand Exchange Constant Screen Rotation With WASD

### ISSUE THREAD

**Issue by daviscook477** [runelite/runelite#6548]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
If going into the grand exchange with the WASD plugin enabled to remap the screen rotation to a character key the grand exchange will constantly rotate if that button (example a in "apple") is pressed before the text box to input your search appears.

**To Reproduce**
1. enable WASD screen rotation
2. go to GE
3. after clicking on the bag icon but **before** the text box appears hold down either a, s, d, or w.
4. once the text box appears release the held down key
5. that screen rotation continues (i.e. if a was held the screen will constantly rotate left)
6. the rotation only goes away after exiting the ge and then pressing and then releasing the offending key.

**Expected behavior**
Once the grand exchange text box appears all rotation due to wasd stops. That way shopping on the grand exchange doesn't make me (and anyone else) really dizzy when this bug appears.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Comment by Adam-** [comment]
Fixed in 77110c4b032df8f6e5b3fa939f90a4fabcc1f657

**Comment by JimmyFrix** [comment]
This is still an issue when rotating the camera while a new region is being loaded the camera rotation will lock until you bring the client out of focus.
