### ISSUE TITLE
GPU Render Causes The Game to Flicker

### ISSUE THREAD

**Issue by DoctaDread** [runelite/runelite#6852]
**Describe the bug**
When I have the GPU setting turned on, it creates a screen flicker that seems random and unpredicatble. It is a white flicker. Almost like the screen is cracked.

**To Reproduce**
1. Turn on GPU at any setting of length

GPU is the only time this happens.

**Expected behavior**
Honestly, I expected to not have a white flicker along my screen.

**Screenshots**
I wish I could capture one...

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.3

**Comment by raku-cat** [comment]
I'm getting this on linux as well, I tried to record it and funnily enough, once I started the window capture in OBS it shows the flicker in the capture but the actual game window stops flickering. Regardless I do still have the recording.
[flickering.zip](https://github.com/runelite/runelite/files/2656343/flickering.zip)

**Comment by MagicfTail** [comment]
Have you tried this? https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by DoctaDread** [comment]
> Have you tried this? https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

I did and it looks like it has gotten worse :o

**Comment by raku-cat** [comment]
@MagicfTail FOr me disabling HW accel did appear to solve it. I would assume doctadread must be having a different issue because their screen is flashing white(mine flashes black) and that solution doesn't work for them.

**Comment by killersloth** [comment]
At least it doesn't look like this 😃 

![untitled](https://user-images.githubusercontent.com/807982/49668950-544f0980-fa25-11e8-8cb5-f6778c604441.png)

**Comment by DoctaDread** [comment]
That's what my game looks like with the x16 anti-aliasing on :D

**Comment by killersloth** [comment]
I only have 1gb of vram with my old hd5450.I can enable it but hopefully it gets optimized a bit to be less memory hungry.

**Comment by Crysikrend** [comment]
> Have you tried this? https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

This worked for me, thank you.

**Comment by hellbringer616** [comment]
suffering from a flickering issue when enabling GPU on Runelite; however my flicker is only with overlay and hud elements.

OS: Ubuntu 19.04
GPU: GTX 1080
GPU driver: nVidia Proprietary driver-418

**Comment by 0fif** [comment]
> suffering from a flickering issue when enabling GPU on Runelite; however my flicker is only with overlay and hud elements.
> 
> OS: Ubuntu 19.04
> GPU: GTX 1080
> GPU driver: nVidia Proprietary driver-418

Yep, also having the same issue. 
Ended up disabling Hardware Acceleration to make it work.

If you downloaded the .jar version of the launcher, run this:

`java -jar Location-of-RuneLite.jar --mode=OFF`

OS: Pop!_OS 18.04 (Basically Ubuntu)
> GPU: GTX 1080Ti
> GPU driver: nVidia Proprietary driver-418.56

**Comment by Voxed** [comment]
I just wanted to note that this seems to be a refresh-rate issue. The flickering UI almost completely disappears after enabling "FPS Control" and setting the target to 30. Also, I only have the issue when playing the game in close to full-screen (1920x1080). 

OS: Xubuntu 18.04.2
GPU GTX 970
GPU driver: Proprietary Nvidia driver version 430.14

**Comment by DarkArc** [comment]
Can confirm limiting the FPS to 30 fixes the UI flickering for me. GTX 2080, 144hz monitors, was seeing a lot of flickering.

**Comment by hisaobush** [comment]
Bringing this problem back in 2020, every solution listed on this thread does not work for me. Even putting them all together and separate. Currently running 144hz on 2080ti. Any additional help would be greatly appreciated.

**Comment by hellbringer616** [comment]
Just an update, still an issue with Ubuntu 19.10
Driver version: 440.59
GPU: GTX 1080 ti

Im noticing based on comments 100% of the issues are nVidia based gpus..

Can anyone with an AMD GPU and Linux test hardware acceleration?

**Comment by Voxed** [comment]
OS: Arch Linux with i3 and picom
GPU: AMD Radeon RX Vega 64
GPU driver: Mesa 20.0

No flickering with the GPU plugin. Likely related to the proprietary nVidia drivers.
Maybe try with Mesa?

**Comment by F-Tahir** [comment]
Also ran into this issue now when switching over to a 155Hz G-sync monitor and a 2070 Super.

Have tried disabling hardware acceleration, made sure G-sync was enabled but no dice. Running without the gpu plugin enabled right now but missing the draw distance. Any further suggestions?

**Comment by fontivan** [comment]
The only way I could resolve this on Windows was to disable G-Sync. When running on Linux I have no issues though.

RTX 2070, 165 Hz monitor

**Comment by Grimweird** [comment]
GPU: GTX 1070 Strix
Driver: 442.59
Windows 10
144hz Dell 2716DG
UI flickers, specifically left side of inventory. --mode=OFF does nothing. Disabling G-sync works, but I'm not going to use that. In runelite options gpu/anti aliasing - disabling it makes the flicker much less noticeable. It doesn't "move" as much.

**Comment by Dyldozer** [comment]
> GPU: GTX 1070 Strix
> Driver: 442.59
> Windows 10
> 144hz Dell 2716DG
> UI flickers, specifically left side of inventory. --mode=OFF does nothing. Disabling G-sync works, but I'm not going to use that. In runelite options gpu/anti aliasing - disabling it makes the flicker much less noticeable. It doesn't "move" as much.

in gsync settings changing gsync to fullscreen only should fix

**Comment by emiljensen2** [comment]
> 
> 
> GPU: GTX 1070 Strix
> Driver: 442.59
> Windows 10
> 144hz Dell 2716DG
> UI flickers, specifically left side of inventory. --mode=OFF does nothing. Disabling G-sync works, but I'm not going to use that. In runelite options gpu/anti aliasing - disabling it makes the flicker much less noticeable. It doesn't "move" as much.

My gsync isn't active at all with runelite even though I have gsync set to fullscreen and windowed. Perhaps try adding runelite/javaw.exe to your nvidia control panel program settings, and setting it to fixed refresh rate so you don't have to disable gsync globally?

**Comment by Grimweird** [comment]
> 
> 
> > GPU: GTX 1070 Strix
> > Driver: 442.59
> > Windows 10
> > 144hz Dell 2716DG
> > UI flickers, specifically left side of inventory. --mode=OFF does nothing. Disabling G-sync works, but I'm not going to use that. In runelite options gpu/anti aliasing - disabling it makes the flicker much less noticeable. It doesn't "move" as much.
> 
> in gsync settings changing gsync to fullscreen only should fix

Yes it should, but I play most of other games in borderless window.

**Comment by Motophan** [comment]
switching to 60Hz no Gsync fixed this for me.

gsync off did not help @ 144hz
Had to be both gsync off and fixed refresh set at 60Hz

windows client latest version 64bit mode.

**Comment by EddBerkel** [comment]
Hey all, I believe I have fixed this. Just bought an RTX 3070 and this began happening ironically. This is how I fixed it.

1. Open Nvidia Control Panel
2. Open Manage 3D Settings Under the 3D Settings Group
3. Select Program Settings
4. Add RuneLite - Look at recently opened programs to find it easily
5. Adjust the following settings
 - Monitor Technology (Set to Fixed Refresh Rate)
 - OpenGL Rendering GPU (Set to your graphics card)
 - Vertical Sync (Turn Off)
6. Click Apply at the bottom
7. Exit and relaunch RuneLite

YMMV, but this worked for me.

**Comment by konkero869** [comment]
> Hey all, I believe I have fixed this. Just bought an RTX 3070 and this began happening ironically. This is how I fixed it.
> 
> 1. Open Nvidia Control Panel
> 2. Open Manage 3D Settings Under the 3D Settings Group
> 3. Select Program Settings
> 4. Add RuneLite - Look at recently opened programs to find it easily
> 5. Adjust the following settings
> 
> * Monitor Technology (Set to Fixed Refresh Rate)
> * OpenGL Rendering GPU (Set to your graphics card)
> * Vertical Sync (Turn Off)
> 
> 1. Click Apply at the bottom
> 2. Exit and relaunch RuneLite
> 
> YMMV, but this worked for me.

same gpu I did all these steps but I don't have a monitor technology option anywhere and im still having this problem

**Comment by Parrryy** [comment]
This is happening for me on my RTX 2060S, the graphics setting is turned off.

**Comment by MESLewis** [comment]
Join us at https://runelite.net/discord in the #support channel so we can fix this issue for you.

**Comment by SuperD00D1988** [comment]
> This is happening for me on my RTX 2070S, the graphics setting is turned off.
> 
> EDIT:
> 
> Following EddBerkel advice worked and for other things that were causing my computer issues

Worked for me too with a 2070s paired with a Lenovo Y27Q20 and LG 27GL83A-B. Only the Lenovo was flickering. It started happening out of nowhere too. Turning off Gsync fixed it, but I wanted gsync on for other games without having to always turn it on and off. Somehow changing those 3 settings exactly as described fixed my flickering on the Lenovo.

**Comment by SuperD00D1988** [comment]
> Hey all, I believe I have fixed this. Just bought an RTX 3070 and this began happening ironically. This is how I fixed it.
> 
> 1. Open Nvidia Control Panel
> 2. Open Manage 3D Settings Under the 3D Settings Group
> 3. Select Program Settings
> 4. Add RuneLite - Look at recently opened programs to find it easily
> 5. Adjust the following settings
> 
> * Monitor Technology (Set to Fixed Refresh Rate)
> * OpenGL Rendering GPU (Set to your graphics card)
> * Vertical Sync (Turn Off)
> 
> 1. Click Apply at the bottom
> 2. Exit and relaunch RuneLite
> 
> YMMV, but this worked for me.

Bro you're insanely amazing! Thank you!!! Wow! First thing I've found online that actually worked for me in quite some time! :D
Worked for me with a 2070s paired with a Lenovo Y27Q20 and LG 27GL83A-B. Only the Lenovo was flickering. It started happening out of nowhere too. Turning off Gsync fixed it, but I wanted gsync on for other games without having to always turn it on and off. Changing those 3 settings exactly as you described fixed my flickering on the Lenovo while having Gsync activated and using Runelite. Guess it doesn't turn Gsync on with Runelite, or whatever, lol.

**Comment by EddBerkel** [comment]
I'm glad it worked for you guys!

**Comment by Frankyy420** [comment]
> Hey all, I believe I have fixed this. Just bought an RTX 3070 and this began happening ironically. This is how I fixed it.
> 
> 1. Open Nvidia Control Panel
> 2. Open Manage 3D Settings Under the 3D Settings Group
> 3. Select Program Settings
> 4. Add RuneLite - Look at recently opened programs to find it easily
> 5. Adjust the following settings
> 
> * Monitor Technology (Set to Fixed Refresh Rate)
> * OpenGL Rendering GPU (Set to your graphics card)
> * Vertical Sync (Turn Off)
> 
> 1. Click Apply at the bottom
> 2. Exit and relaunch RuneLite
> 
> YMMV, but this worked for me.

This fixed me up on the 3080, thank you MVP!

**Comment by MikeSpo** [comment]
@EddBerkel You have saved my eyeballs, you are a gentleman and a scholar.

**Comment by watrick** [comment]
@EddBerkel This fixed worked for me as well. Ty! 

My equipment: Nvidia 3070, Old Lenovo L24q-20 and another LG monitor with G-Sync/FreeSync both connected through DisplayPort. The flickering was only happening on the L24q monitor.

**Comment by SirFancyBacon** [comment]
Just an update, still an issue on Linux
OS: Ubuntu 20.04
Driver version: 460.91.03
GPU: GTX 1080 ti
Refresh rate: 60hz
Resolution: 1920x1080 

using the switch `--mode=OFF` seems be to be the only solution for nvidia users currently
If anyone knows how to disable vsync in nvdia linux drivers please let me know.

**Comment by Motophan** [comment]
I am sorry, but what you are referring to is actually called gnu/linux

**Comment by PhilProft** [comment]
> Hey all, I believe I have fixed this. Just bought an RTX 3070 and this began happening ironically. This is how I fixed it.
> 
> 1. Open Nvidia Control Panel
> 2. Open Manage 3D Settings Under the 3D Settings Group
> 3. Select Program Settings
> 4. Add RuneLite - Look at recently opened programs to find it easily
> 5. Adjust the following settings
> 
> * Monitor Technology (Set to Fixed Refresh Rate)
> * OpenGL Rendering GPU (Set to your graphics card)
> * Vertical Sync (Turn Off)
> 
> 1. Click Apply at the bottom
> 2. Exit and relaunch RuneLite
> 
> YMMV, but this worked for me.

I applied these settings, but noticed there was significant performance degradation when hovering over or interacting with the Runelite sidebar. I turned off the Fixed Refresh Rate and Max FPS, keeping only Vertical Sync (OFF). This solved the flickering for me.

**Comment by Nightfirecat** [comment]
We have recently replaced the GL library used by the GPU plugin. Given that change and that we are not able to reproduce this issue, we are closing this. Please comment if you still experience this issue.
