### ISSUE TITLE
Aerial fishing spots can appear "stuck"

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#7702]
When logging into the client on first load on Molch Island with Cormorant's glove equipped, one or more of the fishing spots may appear "stuck"--that is, drawing a tile marker and icon on a tile where no fish is present, and with the icon notably in the wrong place. (closer to player character head level than at the water level) Of note, such spots will not be highlighted with the dev tools NPC overlay.

**To Reproduce**
1. Go to Molch island and get a bird from Alry the Angler
2. Log out and close the client
3. Launch the client and log in
4. Possibly see error--if no spot is stuck, repeat from (2)

**Expected behavior**
Only the fish NPCs will be highlighted

**Screenshots**
![glitched-fishing-spot](https://user-images.githubusercontent.com/2199511/52186593-308b2280-2820-11e9-902a-f5d4f34eb78a.gif)
![dev-tools-no-spot-highlight](https://user-images.githubusercontent.com/2199511/52186594-308b2280-2820-11e9-80ff-19e89bf39dfc.png)

P.S. Based on some discussion in Discord, this appears to be (possibly) caused by an `NpcDespawned` event being fired before the `NpcSpawned` event for the same NPC, as the despawn event is not deferred, while the spawn event is. With that said, changing NPCMixin to defer the despawn event posting does not fix this issue.

**EDIT**

This can be more easily reproduced by doing the following:

1. Enable FPS limiting, and set it to limit to 1fps always
2. Log in while standing on Molch island
3. Observe many "stuck" spots

**Comment by Adam-** [comment]
I think this was fixed by a combination of db90754ca2c9ccc910886d7cb68b196e0be404f9 and 0821cf216d43265188f4408be29e64f83bc6c286

**Comment by Nightfirecat** [comment]
This can still be reproduced using the alternate steps at the bottom of the original issue:

1. Go to Molch island and get a bird from Alry the Angler
2. Log out and close the client
3. Enable FPS limiting, and set it to limit to 1fps always
4. Log in
5. Observe many "stuck" spots

**Comment by bedmndsn** [comment]
Still happening on east side of island. 
![2019-10-27_12-25-02](https://user-images.githubusercontent.com/52465600/67640065-e9b0f180-f8b4-11e9-87a6-ad60ffb6b953.png)

**Comment by Goofbelly** [comment]
I experienced this today.  Upon logging into Molch Island, I immediately began aerial fishing when this "ghost" spot appeared:
![RuneLite_2020-02-24_11-59-04](https://user-images.githubusercontent.com/23297938/75174092-f546e480-56fd-11ea-8333-183b810b6a89.png)

**Comment by adit-hotstar** [comment]
This is happening quite consistently for me as well. As you can see, there are five fishing spot markers which haven't disappeared.

<img width="1440" alt="Fishing spot markers don't disappear" src="https://user-images.githubusercontent.com/52000721/84480921-eb4bf000-acb2-11ea-9dae-6a30e444d9ee.png">

Steps to reproduce:

1. Go to Molch Island and start aerial fishing.
2. Occasionally, after catching a fish the marker won't disappear.
3. The number of markers that don't disappear keeps increasing.

I'm currently using MacBook Pro with macOS Sierra.

**Comment by aaditmshah** [comment]
Okay, so I think I figured out what's causing this issue. This happens on a bad internet connection. When you get temporarily disconnected then the `NpcDespawned` events are not fired. Hence, when you reconnect the fishing spot tile markers aren't removed.

I see that in the [`onGameStateChanged`](https://github.com/runelite/runelite/blob/3847276416717527ddb920f78d55a22c6181e15e/runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java#L158-L167) handler when the connection is lost then the fishing spots are cleared. Hence, it seems that sometimes when the connection times out, the `GameStateChanged` event is not fired. Here's the relevant error message from `client.log`.

```
2020-07-06 07:44:12 [pool-5-thread-1] WARN  n.r.c.plugins.worldhopper.ping.Ping - error pinging
java.net.ConnectException: Connection timed out (Connection timed out)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/java.net.Socket.connect(Socket.java:558)
	at net.runelite.client.plugins.worldhopper.ping.Ping.tcpPing(Ping.java:98)
	at net.runelite.client.plugins.worldhopper.ping.Ping.ping(Ping.java:55)
	at net.runelite.client.plugins.worldhopper.WorldHopperPlugin.ping(WorldHopperPlugin.java:852)
	at net.runelite.client.plugins.worldhopper.WorldHopperPlugin.pingNextWorld(WorldHopperPlugin.java:810)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The above connection time out prevented the following fishing spots from being despawned. I believe that if we change the game state to `CONNECTION_LOST` in the [catch handler](https://github.com/runelite/runelite/blob/c4595c1b9a9783b1179d3aa0e4e4b31f12970785/runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/ping/Ping.java#L58-L62) of `ping` then this issue would be resolved. We'd also need to restore the game state when the connection comes back.

![Aerial Fishing Glitch](https://user-images.githubusercontent.com/813511/86549956-abe58c00-bf5e-11ea-9862-842639d1d3d0.png)

**Comment by Nightfirecat** [comment]
Here's some more instances of NPCs being removed during game lag (without reaching a disconnect screen) without removing their indicators.
https://www.youtube.com/watch?v=K9Gidm0_-MQ

**Comment by fluxno** [comment]
Im having a nearly identicle problem but with the drift net plugin
![image](https://user-images.githubusercontent.com/93884382/140660953-7cd9e814-3a00-4c94-92d2-5f9d33071a46.png)

**Comment by Adam-** [comment]
I think this is fixed, again, in update 1.8.34+Rev 208

**Comment by Nightfirecat** [comment]
We reverted the internal code change which attempted to fix this.

**Comment by scott-parkhill** [comment]
This is still happening to me @Nightfirecat, on two computers over at least 8 months. In the screenshot, you can also see that mini-map markers also aren't despawning.

![image](https://github.com/runelite/runelite/assets/48695928/4c2a33bb-9156-42a4-9254-c88659cf7960)
