### ISSUE TITLE
Object marker is infinitely duplicated and unremovable

### ISSUE THREAD

**Issue by Alexgopen** [runelite/runelite#8797]
**Describe the bug**
Every time I lay a net trap, it duplicates the object marker, and I cannot remove it.  There are ghosted object markers making the net trap's click area completely black.

**To Reproduce**
1. Set a net trap
2. Put an object mark on the net and the tree
3. Catch the lizard
4. Set another net trap, it creates another mark
5. Catch the lizard and the mark is not removed
6. Repeat forever and the marks stack and are unremovable, resulting in a black polygon

**Expected behavior**
Only one mark should exist here, and I should be able to remove it if I click remove mark, but it's copying a new unremovable mark every time I lay a trap.  

**Screenshots**
https://i.imgur.com/0323vyI.png

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.22.1
 - Launcher version: 1.6.0

**Comment by Alexgopen** [comment]
Was able to find the objectIndicators entry in the .runelite/settings.properties file and remove all of the net trap entries, so the black polygon is gone, but still this bug should be fixed because it should not be leaving ghosted markers.

https://i.imgur.com/pnt928I.png

**Comment by Nightfirecat** [comment]
Is it specifically that trap which duplicated the overlay, or did all of the traps in the area cause that issue?

**Comment by Alexgopen** [comment]
Only the one on which I marked both the tree as well as the net itself while the trap was laid.  On the other one I marked only the tree without issue, but it seems like the net being marked and then collected when I checked the trap was causing issues, because the mark would remain after the trap was gone, and could not be removed at that point, and replacing the trap would add an additional mark.  I ended up having to manually delete a lot of "Net trap" type marks from the settings file, and then afterwards I only marked the trees and not the nets.

**Comment by Jeaper** [comment]
I believe this happens in Tithe Farm as well.
Marking a Tithe Patch, and then doing a run and harvesting, results in the marker becominning very dark when there is nothing planted in them again.
This also about halves my framerate.
![image](https://user-images.githubusercontent.com/3511692/59118282-070a1100-8950-11e9-8d42-57cdad595c99.png)

**Comment by MrFluffums** [comment]
Same as Jeaper, I experienced this in Fossil Island with the hardwood tree patches where I marked the Teak trees. This didn't initially happen and they were marked normally, but upon returning from a farming run, they were darker and unremovable. It may be worth noting that I used the Shift+Right Click "Mark Object."

![image](https://user-images.githubusercontent.com/39612534/59586085-a6917700-90a7-11e9-92fd-30ac7a31a2e0.png)

Third (previously unmarked) tree for reference:

![image](https://user-images.githubusercontent.com/39612534/59586208-fbcd8880-90a7-11e9-9bb9-54e6c52b5f46.png)

**Comment by MrFluffums** [comment]
I spent some time afk and came back to log in on the tile seen here. The 3rd (western) tree is now also bugged in the same manner, despite being fine at the time of logout as pictured above.

![image](https://user-images.githubusercontent.com/39612534/59594821-36d8b780-90ba-11e9-9867-fade2c2a00fe.png)

**Comment by abextm** [comment]
This is fixed by 59886b084ae2740e30c225eb0f2bd79fb41fdbcd, which will be released this coming Thursday.

**Comment by Alexgopen** [comment]
Issue is not fixed
![image](https://user-images.githubusercontent.com/16151797/80059806-882faf80-84f2-11ea-85b5-919e71f8b9c0.png)
