### ISSUE TITLE
Re-downloading client resulted in bug

### ISSUE THREAD

**Issue by RSNeBay** [runelite/runelite#9917]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

Yesterday I was experiencing CPU spikes/freezing so I uninstalled the client and reinstalled it, after the reinstall I encountered massive graphical issues, disabled anti-aliasing and it fixed the graphical issue.  Second issue, when I click 'Maximize' the client filled about 70% of my screen, I can only go full screen with the 'Restore' option.  All of the text within the client are extremely glitchy, can barely read the text in the client not the game.  I went through troubleshooting from similiar issues on here with no success, disabled hardware acceleration, also went through all of the GPU troubleshooting found here: https://github.com/runelite/runelite/wiki/GPU-FAQ 

I'm still unable to use the client as before, have combed through the Nvidia control panel, with no success.  Just really desperate to have this fixed.

**To Reproduce**

I uninstalled the client / reinstalled it and the issue started from there, there is no error. 

**Expected behavior**

To have the client back to where it was before the reinstall, resolution issue and graphical text issue

**Screenshots**
the text in the client:
https://gyazo.com/de3cb2ef9c5a5c88acae85cc99bc8710
https://gyazo.com/f1e22d9ca61f73193d10bff48d192780
https://gyazo.com/6519a88021bd931980808653f54dec28
this is the client in 'maximize'
https://gyazo.com/efeb634ea351abdfc36b9d524808d690

**Environment (please complete the following information):**
Windows 10 Pro/Nvidia RTX 2080

**Additional context**
no log file when I searched for one

**Comment by Trevor159** [comment]
iirc this is not our bug and is some java graphics bug (probably swing?). Turn off custom chrome in the `runelite` plugin settings and it should fix it.

**Comment by RSNeBay** [comment]
> iirc this is not our bug and is some java graphics bug (probably swing?). Turn off custom chrome in the `runelite` plugin settings and it should fix it.

I turned off 'enable custom window chrome' and the issue is still occuring

**Comment by Trevor159** [comment]
> > iirc this is not our bug and is some java graphics bug (probably swing?). Turn off custom chrome in the `runelite` plugin settings and it should fix it.
> 
> I turned off 'enable custom window chrome' and the issue is still occuring

make sure you restarted your client after changing that setting, also post a screenshot after you restarted your client with custom chrome off and the issue persisting.

**Comment by RSNeBay** [comment]
I did a factory restore to resolve the issue, I went through the trouble shooting you mentioned last night Trevor159 and that didn't resolve it.

After restoring my PC it's been fixed. Not sure where the issue was but I dont care anymore because this was complete hell
